version: "3.5"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
  terraform:
    image: hashicorp/terraform:0.11.14
    container_name: terraform
    working_dir: /terraform
    volumes:
      - ./src:/terraform
  aws:
    build: .
    image: awscli
    container_name: aws
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=mock_access_key
      - AWS_SECRET_ACCESS_KEY=mock_access_key
